[build]
  command = ""
  publish = "."

[[redirects]]
  from = "https://www.passthemis.com/*"
  to   = "https://passthemis.com/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/404.html"
  status = 404

[[headers]]
  for = "/support.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
